spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=kullop
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/yt_app?useSSL=false